// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  VariableName = 2,
  Lookup = 3,
  Bool = 4,
  String = 5,
  Number = 6,
  BinaryExpression = 7,
  Div = 8,
  Times = 9,
  Plus = 10,
  Minus = 11,
  FunctionExpr = 12,
  List = 13,
  Dictionary = 14,
  KeyValue = 15
